spring:
  datasource:
    url: jdbc:mysql://${database.url:localhost}:3306/sample?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${database.password:}
    username: ${database.username:root}
